#define STORAGE_CONFIG 1
#define STORAGE_CRASH_DETECTOR 2
#define STORAGE_CRASH_NUM 3
#define STORAGE_CRASH_TIMESTAMPS 4
#define STORAGE_HEALTH_ACTIVITY 5
#define STORAGE_HEALTH_ACTIVITY_START 6
#define STORAGE_ALTITUDE_CLIMB 7
#define STORAGE_ALTITUDE_DESCEND 8
